### ISSUE TITLE
bug: public/cache-output.json does not exist

### ISSUE THREAD

**Issue by slorber** [netlify-labs/netlify-plugin-debug-cache#5]
I wanted to try this plugin but this is what I got:

![image](https://user-images.githubusercontent.com/749374/80820210-bf7b1c00-8bd6-11ea-9cd4-de852bfd1cf1.png)

**Comment by ehmicky** [comment]
Fixed in #7.

**Comment by ehmicky** [comment]
This bug is still happening:

```
ENOENT: no such file or directory, open 'public/cache-output.json' 
```

**Comment by ehmicky** [comment]
No, it's fixed. The problem was due to https://github.com/netlify/buildbot/issues/792 (TLDR: logs are odd when builds are being canceled).
